- .github/workflows/fetch-quickstarts.yml
* github-script v1 was getting a 404 for the branch protection endpoint
* upgraded github-script to v5
* updated calls for breaking changes
> Fix 404 from branch protection jobs

- src/components/InstallButton.js
Swap cookie used in user logged in check from `ajs_user_id` -> `login_service_login_newrelic_com_tokens`
Our working theory was that `ajs_user_id` is set after / during tessen calls, and when users have ad blocker or privacy extensions, the `ajs_user_id` cookie isn't set. This shouldn't happen as frequently (if at all) with the new token, so we expect this new token to work better for determining if someone is a returning user.
Relates to: #32
> Swap cookie used for user logged in check

- src/@newrelic/gatsby-theme-newrelic/components/Layout/Layout.js
- src/pages/500.js
Following the mockup in the ticket, this PR creates a 500 error page for the IO site. 
- It displays at `localhost:8000/500` with a `yarn develop`. I seems to work fine in mobile view.
- I am unsure how to test if it works when the catalog service fails. 
closes https://github.com/newrelic/instant-observability-website/issues/46
> feat: create 500 error page

- .github/workflows/release.yml
- CODE_OF_CONDUCT.md
- README.md
- This PR resolve the issues reported by repo-linter for OSS policies
- I also made markdown linter fixes
- this also adds a release.yml file
> chore: repo-linter-checks

- src/components/OverviewTile.js
JIRA:https://newrelic.atlassian.net/browse/CXPUI-24
Description:In overview section labels are properly aligned
OLD VIEW
NEW VIEW
> chore: aligned the labels

- src/components/OverviewTile.js
- Now the tiles in the overview tab on category landing page are clickable
- on click the of the tile it will open respective tab
> chore: CXPUI-22 chore tiles in overview as clickable

- src/components/GuidedInstallTileMostPopular.js
`Install New Relic` button was set to `position: absolute` in relation to the page `body`. Now it is set to its parent element. 
closes https://github.com/newrelic/instant-observability-website/issues/84
> Install button stays in guided install tile

- src/components/styles.scss
fixes #88 
JIRA:https://newrelic.atlassian.net/browse/CXPUI-40
Description: centered the cookie modal better on mobile views
**OLD VIEW:**
**NEW VIEW**
with different resolutions
@mdumpati review the changes
> bug:cookie banner is not centered

- src/components/Overlay.js
fixes #92 
JIRA ticket: https://newrelic.atlassian.net/browse/CXPUI-34
Description: Mobile View-clicking “outside” the category modal doesn’t close the modal.
Fix: Now whenever click outside in mobile view, will able to close the modal.
> cxpui34 is resolved

- package.json
- src/components/IOSeo.js
- yarn.lock
Changes were made to theme to resolve errors around using tessen when it wasn't loaded. Additionally, using Gatsby's path prefix with tessen was also fixed. So the 404 page should be fixed in the case where tessen isn't loaded, but should also be fixed to work now when it wasn't previously.
Finally, with these tessen changes, we can remove the hardcoded script block we had to get around this problem since tessen is now correctly sourced and should no longer break pages if not loaded.
Relates to: #99
> fix for broken 404 page

- src/pages/index.jsx
UI updates for the Categories `aside` and  mobile `Overlay` elements.
Relates to [NR-1509](https://issues.newrelic.com/browse/NR-1509)
> NR-1509 - Categories UI Updates

- src/components/EmptyTab.js
- src/components/LandingPageFooter.js
- src/components/QuickstartAlerts.js
- src/components/QuickstartDashboards.js
- src/components/QuickstartDataSources.js
- src/components/QuickstartHowToUse.js
- src/components/QuickstartOverview.js
- src/components/WhatsIncluded/Alerts.js
- src/components/WhatsIncluded/Dashboards.js
- src/components/WhatsIncluded/DataSources.js
- src/components/styles.scss
- src/layouts/QuickStartLayout.js
JIRA:https://issues.newrelic.com/browse/NR
Description: 1. header tags updated with few more css changes such as font-weight, button color updated for empty tag
2. Responsiveness fix for browsers
**
*******
**Firefox** screenshots
*******
**
**
**
*******
**Chrome** screenshots
*******
**
**
**
*******
Safari screenshots
*******
**
**
**
**
**
**
**
**
**
**
**
> feat: NR3156 - Heading tags updated

- src/@newrelic/gatsby-theme-newrelic/components/GlobalFooter.js
- src/@newrelic/gatsby-theme-newrelic/icons/feather.js
- src/components/QuickstartTile.js
- src/data/constants.js
- src/pages/index.jsx
- Update styles for quickstart tiles
- remove dark mode code in these components
- remove List vs Grid View code on homepage
- Update feather icon names - there were 3k warnings in the console because of this. There are a few that are coming from the `gatsby-theme`
This does not touch the Featured/Popular sections. They are build off of this component, but there are still a few adjustments that they require, and are handled in other tickets. 
Relates to [NR-1512](https://issues.newrelic.com/browse/NR-1512)
> feat: NR-1512 Quickstart Tiles UI Updates

- src/components/IOBanner.js
add padding to `input` element so text cannot overlap with `x` icon
> NR-5641: Search input text no longer overlaps with x icon

- src/components/LandingBanner/index.js
* CSS Grid was causing the logo to get pushed around by the dashboard
screenshot
* This moves it to being absolutely positioned
> Fix logo centering

- src/components/QuickstartDashboards.js
JIRA:https://issues.newrelic.com/browse/NR-6353
Description:Fix in Carousel images in the landing pages are of different dimensions.
Below are the Screenshots :
For web view:
For mobile view:
> carousel images dimension fix

- src/components/QuickstartDashboards.js
**JIRA ticket**: NR-6457
**Description**:
Show empty description if the dashboards don't have a valid description
**Previous**:
**Now**
> NR-6457: Missing dashboard descriptions

- gatsby-config.js
- package.json
- yarn.lock
`node-sass` is deprecated and does not support the arm64 cpu architecture. This updates the site to use `sass` instead, which is the replacement for `node-sass` and it supports arm64 cpu architectures. 
TLDR: makes it work on M1 macs
> Remove node sass in favor of `sass`

- src/components/IOBanner.js
JIRA : https://issues.newrelic.com/browse/NR-10882
Description:
changed letter-spacing of IO banner text from
-0.001em to -0.03em;
and
-0.5% to -0.005em;
> NR-10882 : updated letter spacing for IO banner text

- src/@newrelic/gatsby-theme-newrelic/components/GlobalFooter.js
- src/layouts/QuickStartLayout.js
JIRA ticket: https://issues.newrelic.com/browse/NR-10893
Description: Social media icons should be in 2 rows like in HP. Needs to be in sync with NR Homepage.
Previous:
Now:
> NR-10893 fix social icons alignment as home page

- src/@newrelic/gatsby-theme-newrelic/components/GlobalFooter.js
JIRA ticket: https://issues.newrelic.com/browse/NR-12727
Description: Added space after copyright section on mobile view
Previous: 
Now:
> NR-12727 - added space after copyright - mobile view

- src/components/GetStartedFooter.js
- src/components/Icons/DoubleUnderlineSVG.js
JIRA: https://issues.newrelic.com/browse/NR-10879
subtask: https://issues.newrelic.com/browse/NR-11779
Description:
1. Added one new svg component for Underline image
2. Added span for 'for free and underline section
3. Added media query for other than mobile screen
4. added same background color for hover of both buttons
5. Alignment of GetStartedFooter in web and mobile view - set padding and removed margin
Before changes:
*******
After Change
*******
> NR-11779: SVG and css for GetFooter section aligned with newrelic

- src/hooks/useQuickstartPreview.js
- src/pages/preview.jsx
* Move parameters that have default values to the end of the
`useQuickstartPreview` hook definition
* Move function to check if the preview server is running out of the
hook itself
> Move default parameters to end of signature

- src/components/IOBanner.js
JIRA ticket: https://issues.newrelic.com/browse/NR-11587
Description: Fixed the banner of the landing page as per the figma design
Figma design: https://www.figma.com/file/Orm0Ro7Zq4Y76jOnBwZW6B/Instant-Observability-I%2FO-v1?node-id=0%3A1
Previous: 
Now:
> NR-11587: show images on banner as per figma

- src/data/quickstart-redirects.json
The cloudflare quickstart has changed it's slug in the past, this makes sure the older link is redirected to the correct one.
> Add redirect for cloudflare

- src/components/QuickstartTile.js
**JIRA ticket**: https://issues.newrelic.com/browse/NR-12565
**Description** : Updated  When I search for 'redis' in search, I'm able to find the Redis integration tile which is overlapping the tile in the right hand side.
**Steps to test**:
1. open the newrelic.com/instant-observability
2. click the search box and search the redis 
**before image**:
**After image**:
> NR-12565 - fixed tile bug on homepage

- src/@newrelic/gatsby-theme-newrelic/components/GlobalFooter.js
- src/components/EmptyTab.js
- src/components/LandingPageFooter.js
JIRA ticket: https://issues.newrelic.com/browse/NR-12704
Description:
1. When we mouse over a link, the colour is changing to grey in NR website. We need to sync with them.
2. View Repo & Build your own in the footer of the Public IO should have hover animation.
> NR-12704: Fixed link color and button animations

- src/components/GuidedInstallTileMostPopular.js
JIRA ticket: https://issues.newrelic.com/browse/NR-15360
Description: Applied "Spinner" component on the "Install New Relic" button.
When user clicks on the button, user will see a spinner right next to "Install New Relic" and then the application will redirect to a new URL
> NR-15360 applied spinner on "Install New Relic" button

- src/@newrelic/gatsby-theme-newrelic/components/GlobalHeader.js
JIRA ticket: https://issues.newrelic.com/browse/NR-15944
Description: Remove the Get Started CTA from the top nav because every I/O page.
Previous:
Now:
> NR-15944 removed 'Get started' link

- src/components/Share.jsx
**JIRA ticket**: https://issues.newrelic.com/browse/NR-20101
**Description**: Added tessen event for social sharing in Public IO quick-start pages
**Steps to test**:
1. open newrelic.com/instant-observability
2. User will see the main page and goto the details page
3. User will see "Share this" buttons
4. when we click a particle social media buttons, the tessen event will be captured
5. To see the captured event, click on query builder select this account (Account: 1478838 - Growth Data Team / TessenJS)
Run the query ( FROM TessenAction SELECT count(*) WHERE (eventName LIKE 'YOUR EVENT NAME')) to see the count of the event.
example:
FROM TessenAction SELECT * WHERE eventName LIKE 'TIO_TessenOnShareClick_instantObservability' FACET buttonClicked
**Screen short of the query builder**:
> NR-20101 : tessen events on social buttons

- yarn.lock
Some new dependencies got added without an update `yarn.lock`, this get's the lock file up to date with the current dependencies.
> Update yarn.lock for react-share

- src/@newrelic/gatsby-theme-newrelic/components/GlobalHeader.js
The header now detects when a user clicks the back button while the mobile menu overlay is open and closes it while navigating.
I chose to use the logic in the gatsby-theme-newrelic [MobileNavigation](https://github.com/newrelic/gatsby-theme-newrelic/blob/develop/packages/gatsby-theme-newrelic/src/components/MobileNavigation.js) component. I was having a lot of styling issues come up when trying to import the component directly. 
I was seeing odd behavior in the local server where sometimes when clicking the hamburger icon, I would have to click it twice to get the overlay to open. I can't seem to reproduce it in a build, so please check this when reviewing.
> Changes to page pathname close mobile menu

- src/components/WhatsIncluded/WhatsIncludedHeader.jsx
- src/templates/QuickstartDetails.js
This PR serves the purpose of rendering the component sections of the Landing Page with content _before_ the sections without content.
> NOTE: Currently, the `Dashboards.jsx` file has the "What's included?" header inside of the component. There will be another PR to address that change. Example of header issues below.
- As mentioned above, there will be another PR for React/CSS changes. That PR will be merged into this `feat` branch so that both changes are merged to `main` at the same time.
1. `Dashboards(0)`, `Alerts(0)`, `Data Sources(1)` -> `Data Sources(1)`, `Dashboards(0)`, `Alerts(0)`
2. `Dashboards(1)`, `Alerts(2)`, `Data Sources(1)` ->  `Dashboards(1)`, `Alerts(2)`, `Data Sources(1)`
3. `Dashboards(0)`, `Alerts(2)`, `Data Sources(1)` ->  `Alerts(2)`, `Data Sources(1)`, …
> Sort quickstart components by available content

- src/@newrelic/gatsby-theme-newrelic/components/GlobalHeader.js
- src/components/Overlay.js
- src/pages/index.jsx
Added a bigger height to the Spinner component that matches the size of the QuickstartTiles to reduce the layout shift on the carousel.
- Performance scores show layout shift for Desktop improves from 0.07 to 0.0
Also, there was a minor bug were the arrow button was visible over the mobile overlay menu in some screen sizes. That has also been resolved in this ticket.
<details>
<summary> <i>Example of the UI bug before fix</i> </summary>
</details>
> Reduce Slick carousel layout shift

- src/components/QuickstartTile.js
Fixes the issue where long quickstart title can cause the summary to overlap the "read more" button. I opted for a CSS based approach instead of Javascript because counting the number of characters in the title and showing/hiding the summary based on that introduces way too many edge cases around changing letter spacing and line spacing.
The CSS approach has one issue, a few tiles that had no overlap now have their summaries hidden. This is because they were already breaking out of their containers, but the title isn't long enough to cause the "read more" overlap.
> Quickstart tile summary overlap

- plugins/gatsby-source-quickstarts/gatsby-node.js
This PR lowercases the filename for screenshots before it hits the fastly side
> lowercase file names

- gatsby-config.js
The previous settings where creating this header for the `/instant-observability/` page, but we really need it on the `/instant-observability` page. This might be a bug with the `gatsby-plugin-gatsby-cloud` plugin and it's interaction with the `pathPrefix` configuration.
> Set `Referrer-Policy: no-referrer-when-downgrade` on all pages

- src/components/QuickstartImg.js
Docs used for solution: https://www.gatsbyjs.com/plugins/gatsby-image/#gatsby-image-props
> Fix quickstart logos cut off

- src/components/QuickstartTile.js
https://issues.newrelic.com/browse/NR-21567
> NR-21567: Alignment for quickstart arrow icon on safari

- src/@newrelic/gatsby-theme-newrelic/pages/404.js
Pull the 404 page into the site from the theme and reduce functionality to work with IO.
**Note**: The preview does not seem to work well with the 404 page, so you'll need to pull it down and `yarn build && yarn serve`
> Shadow 404 page

- src/components/styles.scss
Now that the site background is not white, the default slick arrows are visible on the page. This code hides them. 
before:
> Remove duplicate carousel arrow

- src/components/IOBanner.js
- long strings would previously overlap with the magnifying glass in the input bar.
> Add padding to search input strings

- src/components/QuickstartDashboards.js
I looked for this bug in multiple page widths and in Safari, Chrome, and Firefox on a local build + serve. It appears to be gone, while keeping the desired behavior of the images across breakpoints. Please double check.
> Dashboard images no longer stretch on safari

- src/components/QuickstartDashboards.js
- src/utils/mock_data/content.js
- src/utils/preview/parseHelpers.js
Previously the IMG element was not receiving a src:
`<img alt="Dotnet screenshot 0" class="css-axom38-QuickstartDashboards">`
I am realizing that the issue is that the quickstarts for the regular page and the previews are sending different shapes to the QuickstartDashboard component.
the previews are using fs to just sending an array of screenshot urls in the repo :
``` javascript
0: "http://localhost:3000/dashboards/dotnet/dotnet.png" 
1: "http://localhost:3000/dashboards/dotnet/dotnet02.png" 
2: "http://localhost:3000/dashboards/dotnet/dotnet03.png"
```
while the regular page is getting a graphql response that has nested the screenshot URLs after we added sharp
``` graphql
screenshots {
publicURL
} 
```
> Dashboard screenshots broken in preview

- src/components/LandingBanner/index.js
- src/components/Overlay.js
- src/components/QuickstartDashboards.js
- src/components/QuickstartImg.js
- src/components/SafeImage.js
- src/hooks/useQuickstartPreview.js
I noticed that we were still getting dinged for the images we load "below the fold". As I dug into that I noticed that all of the SVGs in the catalogue were being loaded "eagerly" and that the landing pages were not using the version of the image processed by sharp during build.
This PR does the following:
* Implements a generic `SafeImage` component that uses `GatsbyImage` and falls back to `img` if needed
* Lazy load all SVGs
* Update `QuickstartImg` to use the new image component
* Update dashboard screenshots carousel to use the new image component
* Update landing banner image to use the new image component
* Various linting fixes
> More image improvements

- CONTRIBUTING.md
- README.md
- src/components/IOSeo.js
- src/data/quickstart-metadata.json
- src/templates/QuickstartDetails.js
https://issues.newrelic.com/browse/NR-35139
The `description` prop doesn't seem to be used in `IOSeo.js`.  Can we remove it?
I am depending on the slug being the first part of the url which appears to work.  Please let me know if theres a case where this isn't true.
I did some reading on character limits for meta title/descriptions. It seems the limit for title is ~70 and description ~160. However these are apparently automatically truncated if they are too long, so I did not do any manual truncating of the strings and wanted to leave this open for discussion.
> NR-35139: Add ability to set custom meta titles and descriptions

- .eslintrc.js
- src/components/GoToTopButton.js
- src/components/QuickstartGrid.js
- src/pages/index.jsx
* We missed some imports from the default theme exporter file during PR
review
* This lead to our bundle size being increase back to what it was before
we worked on it
* This corrects those imports and adds an eslint rule to help us avoid
this issue in the future
* Also renames QuickstartGrid to `js` instead of `jsx` so that eslint
picks it up
> Re-reduce bundle size

- src/@newrelic/gatsby-theme-newrelic/components/SearchInput.js
this removes a z-index that was causing the search icons to appear over the header when a search term was present and the user scrolled down the page. 
Before:
After:
> chore: search icons don't appear on top of header

- src/components/Markdown.js
- src/components/QuickstartOverview.js
We didn't include pre tags in the allowed elements for markdown before so codeblocks didn't render. This adds the tag to the allow list and adds a bit of styling. We actually don't have any codeblocks in quickstart descriptions at the moment (probably because they would disappear before) but here's a screenshot of markdown from an old description:
> Add pre tag to markdown component

- src/utils/preview/parseHelpers.js
fixes bug that doesn't load quickstart previews if contributor excludes the `level` key in their config yaml. 
The example PR now loads without redirecting back to the home page:
> fix: add optional chaining to support level

- src/utils/allFilteredQuickstarts.js
This was causing a bug in Firefox that caused the urls that showed on hover of a quickstart to off by one - they still navigate to their correct pages though. 
However after some investigation, we noticed that only Firefox had Codestream being forced to the front of the Quickstarts at all and we learned that the sorting function was the root of this bug. Coincidentally, we think marketing no longer wants Codestream in the front so this has gone unnoticed until now. 
This PR also removes the code that shift codestream to the top.
> Remove Codestream shift to top
