newrelic/instant-observability-website

- gatsby-config.js
closes: https://github.com/newrelic/developer-website/issues/2005
> [New I/O Site] Analytics

- gatsby-config.js
- src/@newrelic/gatsby-theme-newrelic/components/GlobalFooter.js
- src/pages/index.jsx
This PR removes the build your own tile and replaces the create issue button with build your own.
> chore: removed build your own tile

- src/pages/index.jsx
removed featured tag from pack tile
> chore: CXPUI-7 removed feature tag from pack tile

- src/data/quickstarts.json
removed unwanted most popular key words
> chore: CXPUI-12 chore updated quick start json

- src/pages/index.jsx
JIRA:https://newrelic.atlassian.net/browse/CXPUI-26
Description:When user selects a category in left navigation pane carousel of most popular and featured are supposed to be hidden
**OLD VIEW:**
when All option selected in left panel
when any category is selected
**NEW VIEW:**
when All option selected in left panel
when any category is selected
> Chore:hidding the carousel when we select any category

- README.md
We used the wrong image path for this community project snippet so I fixed it using the correct one, this should appease repo-linter 🤞
> chore: swaps commmunity project image

- src/templates/QuickstartDetails.js
fixes #86
JIRA ticket: https://newrelic.atlassian.net/browse/CXPUI-39
Description: Code stream quickstart CSS issue with logo - zoom out more than 100%, logo started becoming small
Fix: Now Logo has no issue while zoom out
https://user-images.githubusercontent.com/101187392/158658161-8fc17936-50ed-4d92-9d18-a8d7367f33a4.mov
https://user-images.githubusercontent.com/101187392/158658187-e5020e48-9417-478e-a4ca-206997214bdc.mov
.
> Code stream quickstart CSS issue with logo

- .releaserc
- package.json
- yarn.lock
Adds a `.releaserc` file so that we can generate a changelog and github releases
> Add release config file

- gatsby-node.js
- src/data/quickstart-redirects.json
JIRA: https://newrelic.atlassian.net/browse/CXPUI-45
Description: handle redirects for URLs when a quickstart name changes
Fix: added new redirect json file and createRedirects action to generate any redirects
> chore: CXPUI 45 : Handle redirects for URL when quickstart name changes

- package.json
- src/@newrelic/gatsby-theme-newrelic/components/GlobalHeader.js
- src/components/styles.scss
- yarn.lock
JIRA:https://newrelic.atlassian.net/browse/CXPUI-33
Description:The global header of I/O website had changed to look similar to the main page header of new relic website.
Screenshots Attached:
**OLD VIEW**
Mobile view:
**NEW VIEW**
In dark mode:
MOBILE VIEW:
> chore:changes in header to look similar to Main page of New Relic website

- src/@newrelic/gatsby-theme-newrelic/components/GlobalHeader.js
- src/components/LandingPageFooter.js
- src/components/PageLayout/Header.js
- src/components/QuickstartOverview.js
- src/components/styles.scss
Description:Some of the  bugs are fixed related to css
> bug fixing

- src/pages/index.jsx
> NR-5908: Remove excess whitespace in mobile view

- src/components/GetStartedFooter.js
This will update the buttons in the "Get started today" footer to use the semantic-token-style class names and colors for the "primary" and "primary-accent" buttons.
Previously, the buttons were a slightly different color. Furthermore, they didn't have the correct hover treatment.
* NR-5642
> Update sign-up buttons in footer

- src/components/InstallButton.js
- src/components/styles.scss
JIRA: https://issues.newrelic.com/browse/NR-6460
Description: Changed background color from white to green for hero section
Before Change:
After changes:
> NR-6460 : background color changed to green in hero section

- src/@newrelic/gatsby-theme-newrelic/components/GlobalFooter.js
- src/@newrelic/gatsby-theme-newrelic/components/GlobalHeader.js
- src/components/GuidedInstallTileMostPopular.js
- src/components/IOBanner.js
- src/components/QuickstartTile.js
- src/pages/index.jsx
- src/templates/QuickstartDetails.js
Fonts were showing up with different looking weights between browsers. This removes a lot of hard coded font weights and makes them look similar between browsers.
Please compare this side-by-side with chrome, firefox, and safari.
> Font issues on Safari and Firefox

- src/components/LandingBanner/BannerBackground.js
- src/components/LandingBanner/index.js
- src/templates/QuickstartDetails.js
https://issues.newrelic.com/browse/NR-5627
min-height to make the banner size dynamic seems to fix this issue.  Adding vw text sizes and media queries to adjust text based on screen size.
> NR-5627 Fix issue with banner height and margin

- src/pages/index.jsx
Description: updated carousel arrow on home page 
After change
********
********
Before change
********
> changed carousel arrow for home page

- src/hooks/useLocalhostQuickstart.js
- src/pages/preview.jsx
- src/utils/preview/fetchHelpers.js
https://issues.newrelic.com/browse/NR-2231
Depends on parseHelpers.js from [#192](https://github.com/newrelic/instant-observability-website/pull/192)
> NR-2231 Fetch files from localhost

- src/@newrelic/gatsby-theme-newrelic/components/GlobalFooter.js
JIRA ticket: https://issues.newrelic.com/browse/NR-10853
Description: Footer Copyright text - Make it dynamic for the existing year.
> NR-10853: Apply dynamic year on copyright content

- src/components/AnimatedText.js
- src/components/GetStartedFooter.js
- src/components/InstallButton.js
JIRA: https://issues.newrelic.com/browse/NR-10857
Description: 
1. In GetStartedFooter component, value of **--nr1--color--text--buttton--primary** updated.
2. Added animations for both buttons- ' Sign Up' and 'Get Demo'
Before change
*******
After change
*******
> NR-10857-GetStartedFooter SignUp text color updated to Green and now it is animated

- src/components/styles.scss
- src/pages/index.jsx
JIRA: https://issues.newrelic.com/browse/NR-10861
Description: Left side of home page- **Categories** -> color updated.
background color:  #E4E5E6
text color: #1D252C
Before change
*******
After change
*******
> NR-10861 : category hover color updated

- src/@newrelic/gatsby-theme-newrelic/components/GlobalFooter.js
- src/data/constants.js
JIRA: https://issues.newrelic.com/browse/NR-10879
subtask :  https://issues.newrelic.com/browse/NR-11778
Description:
1. Added hyperlink to New Relic.com Logo in the footer and point it to http://newrelic.com/
2. Link to ESG is added now in Public IO while comparing all the 12 links with NR HP footer.
> NR-10879 : added ESG in Resources and hyperlink to new relic logo on footer section

- src/@newrelic/gatsby-theme-newrelic/components/GlobalFooter.js
- src/layouts/QuickStartLayout.js
JIRA tickets: https://issues.newrelic.com/browse/NR-10888
Description:
For the homepage section of the Public IO, we need to have TOS, DMCA, Privacy should be in one column. Cookie, UK Slavery Act in 2nd column.
Previous:
Now:
> NR-10888: TOS, DMCA, Privacy should be in one column. Cookie, UK Slavery Act in 2nd column.

- src/components/LandingPageFooter.js
* QUICKSTARTS_REPO was not being imported here, this did not break
because a quickstart will never not have a packUrl.
* Some formatting fixes as well
> Add import for QUICKSTARTS_REPO

- src/utils/preview/parseHelpers.js
* Add placeholders for alerts
* Add multi-doc parsing for alerts, but only take first
* Add placeholders and JSON parse try/catch for dashboards
> Handle empty files

- src/hooks/useQuickstartPreview.js
* Add instrumentation to preview hooks
* Both have a general event that fires on page load and an event for
errors
* Remove unneeded `await`
> Add instrumentation

- src/pages/index.jsx
**JIRA ticket**: https://issues.newrelic.com/browse/NR-15277
**Description** : Removed scrolling feature for left sidebar
**Steps to test**:
1. open the newrelic.com/instant-observability
2. mouse scroll Up and Down in Categories of left sidebar
**before changes**:
**After changes**:
> Fix/NR-15277: Removed category scroll

- src/@newrelic/gatsby-theme-newrelic/components/GlobalHeader.js
- src/components/styles.scss
- src/pages/index.jsx
JIRA : https://issues.newrelic.com/browse/NR-11585
subtask: https://issues.newrelic.com/browse/NR-12569
Description: 
1. Header is sticky in web view and non-sticky in mobile view
2. z-index=0 applied for header  bottom border line in mobile view
3. new relic logo size lesser in mobile view than web view
4. adjusted font-size and height
5. hover color is now same.
After change
Before change
> NR-12569 :  header section in mobile and web view

- src/components/GuidedInstallTileMostPopular.js
JIRA ticket: https://issues.newrelic.com/browse/NR-15360
Description: Remove underline for the icon on clicking "Install New Relic" link on "Guided Install" card
Prev:
Now:
> NR-15360-update

- src/@newrelic/gatsby-theme-newrelic/components/GlobalHeader.js
JIRA ticket: https://issues.newrelic.com/browse/NR-15628
Description:
1. User will see "Get started" link in the main page
2. User will not see "Get started" link in the details page
**Previous** :
Mobile:
**new**:
Mobile:
> NR-15628: get-started-cta

- src/pages/index.jsx
**Jira ticket:** https://issues.newrelic.com/browse/NR-20578.
**Description:**  Updated the Go to Top button border style.
**Screenshots:**
> fix/NR-20578: updated the style of Go to top button

- src/@newrelic/gatsby-theme-newrelic/components/SearchInput.js
- src/@newrelic/gatsby-theme-newrelic/hooks/useSyncedRef.js
- src/@newrelic/gatsby-theme-newrelic/utils/composeHandlers.js
- src/components/IOBanner.js
- src/pages/index.jsx
JIRA ticket: https://issues.newrelic.com/browse/NR-19410
Description:
Remove on the fly search and apply search on clicking "Enter" button or by clicking on the search button on the input field
Prev:
Now:
> NR-19410: Enhancement - Search Functionality

- src/components/QuickstartTile.js
https://issues.newrelic.com/browse/NR-21599
> NR-21599 Remove margin fixes QuickstartTile width

- gatsby-config.js
https://issues.newrelic.com/browse/NR-20527
> Add mergeCachingHeaders option to gatsby cloud config

- gatsby-node.js
- jest.config.js
- src/@newrelic/gatsby-theme-newrelic/components/GlobalFooter.js
- src/@newrelic/gatsby-theme-newrelic/components/Logo.js
- src/@newrelic/gatsby-theme-newrelic/components/SearchInput.js
- src/components/EmptyTab.js
- src/components/GetStartedFooter.js
- src/components/GuidedInstallTile.js
- src/components/GuidedInstallTileMostPopular.js
- src/components/IOBanner.js
- src/components/InstallButton.js
- src/components/LandingBanner/BannerBackground.js
- src/components/LandingPageFooter.js
- src/components/QuickstartHowToUse.js
- src/components/QuickstartTile.js
- src/components/Share.jsx
- src/components/SideBySide.js
- src/components/SupportSection.js
- src/components/WhatsIncluded/Dashboards.js
- src/hooks/usePageLayout.js
- src/hooks/useQuickstartPreview.js
- src/layouts/QuickStartLayout.js
- src/layouts/index.js
- src/pages/index.jsx
- src/pages/preview.jsx
- src/templates/QuickstartDetails.js
- src/types.js
- src/utils/preview/fetchHelpers.js
- src/utils/preview/parseHelpers.js
https://issues.newrelic.com/browse/NR-20054
> NR-20054 alias components directory in webpack config

- src/hooks/useQuickstartPreview.js
- src/utils/preview/fetchHelpers.js
- src/utils/preview/parseHelpers.js
https://issues.newrelic.com/browse/NR-26667
> NR-26667 PR Preview updates for new structure

- src/pages/index.jsx
https://issues.newrelic.com/browse/NR-21565
I'm not sure if I'm a big fan of this solution, but it seems to fix the issue.  Putting it up for discussion and ideas.
> NR-21565 Fix overlapping banner and categories input

- .github/workflows/run-lint.yml
- .github/workflows/run-tests.yml
https://issues.newrelic.com/browse/NR-30287
> NR-30287: --frozen-lockfile for workflows

- src/components/QuickstartDashboards.js
- src/components/styles.scss
- src/pages/index.jsx
this aligns the edges of the carousel slides with its headers and also with the sidebar headers
> Align catalog headers and carousel margins

- src/components/InstallButton.js
- src/components/LandingBanner/index.js
- src/components/LandingPageFooter.js
- src/components/QuickstartAlerts.js
- src/components/QuickstartDashboards.js
- src/components/QuickstartDataSources.js
- src/components/QuickstartOverview.js
- src/templates/QuickstartDetails.js
- src/utils/sortedQuickstartComponents.js
Reverts newrelic/instant-observability-website#282
> Revert "Test cache issues"

- .github/workflows/clear-website-cache.yml
- README.md
Adds a workflow to clear the website's fastly cache whenever we push new code. This workflow can also be triggered via a workflow run.
> Add workflow to clear cache on push

- src/components/QuickstartDocumentation.js
- src/components/WhatsIncluded/Documentation.js
- src/templates/QuickstartDetails.js
- src/utils/sortedQuickstartComponents.js
> Datasources to Documentation

- src/components/GoToTopButton.js
https://issues.newrelic.com/browse/NR-21595
I found when running the app in development on firefox it crashes entirely for me.  There are many errors in the console as well.  To address this error specifically I tested this in staging but we may want to look into the development errors in firefox, assuming they aren't specific to my browser/machine.
> Error navigating to landing pages

- src/data/quickstart-metadata.json
Previous: 
Title: 
Python | New Relic Instant Observability
Description: 
New Relic&#x27;s instant observability quickstart boasts alerts, event loop diagnostics, and multiple customizable dashboards to detect and resolve issues before they impact end-users.
Now:
Title:
Python Application Performance Monitoring | New Relic
Description:
Python monitoring tool by New Relic helps business users and developers monitor Python application performance
I made changes on quickstart-metadata.json and then I have executed the code. But on http://localhost:8000/python/986df593-98db-485b-8e8c-dd866fa28813, I am not able to observe the updated title and description. Kindly guide me if I am going wrong somewhere.
Thank you. 🙂
> Added metadata for python page

- .eslintrc.js
- jest.config.js
- package.json
- src/utils/__tests__/searchRanking.test.js
- src/utils/allFilteredQuickstarts.js
- src/utils/searchRanking.ts
- yarn.lock
- Adds search ranking
- Ranking is defined by a list of rules that check for things like exact string match, word match, substring match, etc.
- These rules are defined in priority order
- Make eslint ignore generated gatsby types
> Search ranking

- src/pages/index.jsx
https://issues.newrelic.com/browse/NR-42569
> Always show guided install

- src/components/IOSeo.js
https://issues.newrelic.com/browse/NR-42524
> Add crazy egg for 3 new pages

- src/@newrelic/gatsby-theme-newrelic/components/GlobalHeader.js
- src/components/InstallButton.js
- src/templates/QuickstartDetails.js
https://issues.newrelic.com/browse/NR-41180
This PR:
1. Disables the click from the New Relic logo in the header when `utm_medium` is set.
2. Hides the header navigation when `utm_medium` is set
3. Adds the entire urlParams object to instrumentation for install button.
> NR-41180: Marketing changes

- gatsby-node.js
- src/utils/resolveQuickstartSlug.js
https://issues.newrelic.com/browse/NR-42935
> Change URLs to be simple, Create pages with uuids 

- src/data/quickstart-metadata.json
update the page title and meta description of top 26 quick-starts.
list of the quickstarts
1. Amazon web services
2. Apache
3. CircleCI
4. CodeStream
5. Databricks
6. Django
7. .Net
8. Express
9. FastAPI
10. Flask
11. IBM MQ
12. Java
13. Kafka
14. Lacework
15. Laravel
16. MongoDB
17. MySQL
18. NGINX
19. PHP
20. Redis
21. Salesforce Event logs
22. Slack notifications
23. Synthetics SSL certification
24. Apache Tomcat
25. WordPress
26. Python
> refactor(Quickstarts): Updated the meta details of 26 quickstarts

- src/@newrelic/gatsby-theme-newrelic/components/GlobalHeader.js
- src/data/constants.js
https://issues.newrelic.com/browse/NR-46561
> Marketing pages only on specific utm codes

- src/data/quickstart-metadata.json
**Ticket URL's:** 
1. https://issues.newrelic.com/browse/NR-31187
2. https://issues.newrelic.com/browse/NR-31202
3. https://issues.newrelic.com/browse/NR-30929
4. https://issues.newrelic.com/browse/NR-31209
**Description:** 
Updated new quickstarts (Ansible tower, C# and Typescript) titles and descriptions in the metadata file.
> Updated new quickstarts titles and description.

- gatsby-ssr.js
- gatsby/on-render-body.js
https://issues.newrelic.com/browse/NR-52304
> NR-52304: Add gatsby-ssr file

- src/data/quickstart-metadata.json
**Ticket URL's:**
1. https://issues.newrelic.com/browse/NR-56439
2. https://issues.newrelic.com/browse/NR-41158
**Description:**
Updated new quickstarts (Apache-Flink and Snowflake) titles and descriptions in the metadata file.
> Updated metadata IO page titles and descriptions for flink and snowflake

- package.json
- src/components/LandingBanner/BannerBackground.js
- src/components/LandingBanner/index.js
- src/components/LandingPageFooter.js
- src/data/constants.js
- src/layouts/QuickStartLayout.js
- yarn.lock
This incorporates a Tessen fix along with a Gatsby gql fix
> fix: update theme version to 6.13.6

- src/data/instant-observability-categories.json
> Add Prometheus and Security categories

- gatsby-config.js
- package.json
- src/components/InstallButton.js
- yarn.lock
this replaces the ad hoc logic with a new hook from the theme. also adds the `newRelicRequestingServicesHeader` theme option
wait for [gatsby-theme-newrelic#826](https://github.com/newrelic/gatsby-theme-newrelic/pull/826) to be released before merging this
> use `useLoggedIn` hook from theme
